"""add telegram_id to user

Revision ID: 22934ffd6615
Revises: 318dc4bde8a1
Create Date: 2026-04-25 20:00:00.720429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22934ffd6615'
down_revision: Union[str, Sequence[str], None] = '318dc4bde8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram_id'))
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
