"""add telegram link code

Revision ID: 4ee76605d477
Revises: 6bedb5aad614
Create Date: 2026-06-10 03:54:53.244403

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ee76605d477"
down_revision: Union[str, Sequence[str], None] = "6bedb5aad614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("telegram_link_code", sa.String(length=32), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["telegram_link_code"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("telegram_link_code")

    # ### end Alembic commands ###
