"""add last reminder at to workout schedule

Revision ID: 6bedb5aad614
Revises: 2a9e09b0cd7c
Create Date: 2026-06-04 23:10:52.768531

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bedb5aad614"
down_revision: Union[str, Sequence[str], None] = "2a9e09b0cd7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workoutschedule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workoutschedule", schema=None) as batch_op:
        batch_op.drop_column("last_reminder_at")

    # ### end Alembic commands ###
