"""Initial revision

Revision ID: 8bd6fc6fa61f
Revises: 3f8c1e4f8067
Create Date: 2026-05-18 21:01:29.938973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd6fc6fa61f'
down_revision: Union[str, Sequence[str], None] = '3f8c1e4f8067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram_id'))
        batch_op.create_unique_constraint(None, ['telegram_id'])

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workoutexercise_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workoutexercise_workout_id'), ['workout_id'], unique=False)

    with op.batch_alter_table('workoutlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workoutlog_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workoutlog_user_id'))

    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workoutexercise_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workoutexercise_exercise_id'))

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_created_at'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_user_telegram_id'), ['telegram_id'], unique=True)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_created_at'))

    # ### end Alembic commands ###
